openapi: 3.1.3
info:
  title: Swagger Go api - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: http://localhost:8080
paths:
  /users/:
    get:
      tags:
        - users
      summary: get users
      description: Returns list
      parameters:
        - in: query
          required: false
          name: sort
          schema:
            type: string
            example: id--desc
          description: sort field-direction
        - in: query
          required: false
          name: filter
          schema:
            type: string
            example: login--test1
          description: field to filter-value
      security:
        - basicAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersList"
        "400":
          description: Invalid route
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: basicAuth
  schemas:
    UsersList:
      type: object
      properties:
        Success:
          type: boolean
          example: true
        Message:
          type: array
          items:
            $ref: "#/components/schemas/Users"
        Total:
          type: integer
          example: 2
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
    User:
      type: object
      properties:
        checklists_quantity:
          type: integer
          example: 2
        created_at:
          type: string
          example: "2025-05-11T00:00:00Z"
        email:
          type: string
          example: "admin@admin.com"
