openapi: 3.1.3
info:
  title: Swagger Go api - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: http://localhost:8080
paths:
  /users/:
    get:
      tags:
        - users
      summary: get users
      description: Returns list
      parameters:
        - in: query
          required: false
          name: sort
          schema:
            type: string
            example: id--desc
          description: sort field-direction
        - in: query
          required: false
          name: filter
          schema:
            type: string
            example: login--test1
          description: field to filter-value
      security:
        - basicAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersList"
        "400":
          description: Invalid route
    post:
      tags:
        - users
      summary: Add a new users
      description: Add a new user, return its id
      requestBody:
        description: Create a new users
        required: true
        content:
          application/json:
            schema:
              required:
                - "login"
                - "password"
                - "email"
                - "role_id"
              properties:
                login:
                  description: Login
                  example: test1
                  type: string
                password:
                  type: string
                  example: "12345aA!!"
                email:
                  type: string
                  example: "admin@admin.com"
                role_id:
                  type: integer
                  example: 1
      security:
        - basicAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreationSuccess"
        "400":
          description: Invalid input
        "422":
          description: Validation exception
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: basicAuth
  schemas:
    UsersList:
      type: object
      properties:
        Success:
          type: boolean
          example: true
        Message:
          type: array
          items:
            $ref: "#/components/schemas/Users"
        Total:
          type: integer
          example: 2
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
    User:
      type: object
      properties:
        checklists_quantity:
          type: integer
          example: 2
        created_at:
          type: string
          example: "2025-05-11T00:00:00Z"
        email:
          type: string
          example: "admin@admin.com"
        id:
          type: integer
          example: 1
        login:
          type: string
          example: "test1"
        role_id:
          type: integer
          example: 1
    CreationSuccess:
      type: object
      properties:
        Success:
          type: boolean
          example: true
        Message:
          type: object
          properties:
            id:
              type: integer
              example: 1
