openapi: 3.1.3
info:
  title: Swagger Go api - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: http://localhost:8080
paths:
  /users/:
    get:
      tags:
        - users
      summary: get users
      description: Returns list
      parameters:
        - in: query
          required: false
          name: sort
          schema:
            type: string
            example: id--desc
          description: sort field-direction
        - in: query
          required: false
          name: filter
          schema:
            type: string
            example: login--test1
          description: field to filter-value
      security:
        - basicAuth: []
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid route
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: basicAuth