openapi: 3.1.3
info:
  title: Swagger Go api - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: http://localhost:8080
paths:
  /users/:
    get:
      tags:
        - users
      summary: get users
      description: Returns list
      parameters:
        - in: query
          required: false
          name: sort
          schema:
            type: string
            example: id--desc
          description: sort field-direction
        - in: query
          required: false
          name: filter
          schema:
            type: string
            example: login--test1
          description: field to filter-value
      security:
        - basicAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersList"
        "400":
          description: Invalid route
    post:
      tags:
        - users
      summary: Add a new user
      description: Add a new user, return its id
      requestBody:
        description: Create a new user
        required: true
        content:
          application/json:
            schema:
              required:
                - "login"
                - "password"
                - "email"
                - "role_id"
              properties:
                login:
                  description: Login
                  example: test1
                  type: string
                password:
                  type: string
                  example: "12345aA!!"
                email:
                  type: string
                  example: "admin@admin.com"
                role_id:
                  type: integer
                  example: 1
      security:
        - basicAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActionSuccess"
        "400":
          description: Invalid input
        "422":
          description: Validation exception
  /users/{id}:
    put:
      tags:
        - users
      summary: update user
      description: update user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 3
          description: user id
      requestBody:
        description: update user
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  example: 1@123test-updated.com
                name:
                  type: string
                  example: testUpdatedLogin1
              type: object
      security:
        - basicAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActionSuccess"
        "400":
          description: Invalid input
        "422":
          description: Validation exception
    delete:
      tags:
        - users
      summary: delete user
      description: delete user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 9
          description: user id
      security:
        - basicAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActionSuccess"
        "400":
          description: Invalid input
        "422":
          description: Validation exception
  /roles/:
    get:
      tags:
        - roles
      summary: get roles
      description: Returns list
      parameters:
        - in: query
          required: false
          name: sort
          schema:
            type: string
            example: id--desc
          description: sort field-direction
        - in: query
          required: false
          name: filter
          schema:
            type: string
            example: title--Admin
          description: field to filter-value
      security:
        - basicAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RolesList"
        "400":
          description: Invalid route
    post:
      tags:
        - roles
      summary: Add a new role
      description: Add a new role, return its id
      requestBody:
        description: Create a new role
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataForCreatingRole"
      security:
        - basicAuth: []
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActionSuccess"
        "400":
          description: Invalid input
        "422":
          description: Validation exception
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: basicAuth
  schemas:
    UsersList:
      type: object
      properties:
        Success:
          type: boolean
          example: true
        Message:
          type: array
          items:
            $ref: "#/components/schemas/Users"
        Total:
          type: integer
          example: 2
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
    User:
      type: object
      properties:
        checklists_quantity:
          type: integer
          example: 2
        created_at:
          type: string
          example: "2025-05-11T00:00:00Z"
        email:
          type: string
          example: "admin@admin.com"
        id:
          type: integer
          example: 1
        login:
          type: string
          example: "test1"
        role_id:
          type: integer
          example: 1
    ActionSuccess:
      type: object
      properties:
        Success:
          type: boolean
          example: true
        Message:
          type: object
          properties:
            id:
              type: integer
              example: 1
    RolesList:
      type: object
      properties:
        Success:
          type: boolean
          example: true
        Message:
          type: array
          items:
            $ref: "#/components/schemas/Roles"
        Total:
          type: integer
          example: 2
    Roles:
      type: array
      items:
        $ref: "#/components/schemas/Role"
    Role:
      type: object
      properties:
        abilities:
          type: object
          properties:
            users:
              $ref: "#/components/schemas/Abilities"
            roles:
              $ref: "#/components/schemas/Abilities"
            checklists:
              $ref: "#/components/schemas/Abilities"
            checklists_items:
              $ref: "#/components/schemas/Abilities"
        created_at:
          type: string
          example: "2025-05-11T00:00:00Z"
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Admin"
    Abilities:
      type: object
      properties:
        create: 
          description: 1 possible, 0 not available
          type: integer
          example: 1
        read:
          description: 1 possible, 0 not available
          type: integer
          example: 1
        update:
          description: 1 possible, 0 not available
          type: integer
          example: 0
        delete:
          description: 1 possible, 0 not available
          type: integer
          example: 0
    DataForCreatingRole:
      type: object
      properties:
        abilities:
          type: object
          properties:
            users:
              $ref: "#/components/schemas/Abilities"
            roles:
              $ref: "#/components/schemas/Abilities"
            checklists:
              $ref: "#/components/schemas/Abilities"
            checklists_items:
              $ref: "#/components/schemas/Abilities"
        title:
          type: string
          example: "User123"
